# Generated by Django 3.2 on 2021-05-04 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('cod_bills', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('dead_line', models.DateField(blank=True, null=True)),
                ('attachment', models.BinaryField(blank=True, null=True)),
                ('paid_day', models.DateField(blank=True, null=True)),
                ('dt_from', models.DateField(blank=True, null=True)),
                ('dt_to', models.DateField(blank=True, null=True)),
                ('send', models.BooleanField(blank=True, null=True)),
                ('mime_type_old', models.CharField(blank=True, max_length=10, null=True)),
                ('mime_type_res', models.CharField(blank=True, max_length=10, null=True)),
                ('mime_type_99', models.CharField(blank=True, db_column='MIME_TYPE_99', max_length=10, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bills',
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('cod_bill_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='type', max_length=100, null=True)),
            ],
            options={
                'db_table': 'bill_type',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('cod_house', models.AutoField(primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=255)),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'house',
            },
        ),
        migrations.CreateModel(
            name='Residents',
            fields=[
                ('cod_resident', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('couple', models.BooleanField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_in', models.DateField(blank=True, null=True)),
                ('dt_out', models.DateField(blank=True, null=True)),
                ('cod_house', models.ForeignKey(db_column='cod_house', on_delete=django.db.models.deletion.PROTECT, to='split_bills_app.house', verbose_name='House')),
            ],
            options={
                'verbose_name_plural': 'Residents',
                'db_table': 'residents',
            },
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('cod_split', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('split_date', models.DateField(blank=True, null=True)),
                ('payed_day', models.DateField(blank=True, null=True)),
                ('cod_bills', models.ForeignKey(db_column='cod_bills', on_delete=django.db.models.deletion.DO_NOTHING, to='split_bills_app.bills')),
                ('cod_resident', models.ForeignKey(db_column='cod_resident', on_delete=django.db.models.deletion.DO_NOTHING, to='split_bills_app.residents')),
            ],
            options={
                'db_table': 'split',
            },
        ),
        migrations.AddField(
            model_name='bills',
            name='cod_bill_type',
            field=models.ForeignKey(db_column='cod_bill_type', on_delete=django.db.models.deletion.DO_NOTHING, to='split_bills_app.billtype'),
        ),
        migrations.AddField(
            model_name='bills',
            name='cod_house',
            field=models.ForeignKey(db_column='cod_house', on_delete=django.db.models.deletion.DO_NOTHING, to='split_bills_app.house'),
        ),
    ]
